[ARC-1931] created layouts
AleksandreGalogreBaramidze/TaskPlanner pull request #1
Opened 2021-11-25 07:44 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1931

2021-11-25 07:49 UTC, GiorgiMamagulashvili16 requested changes

2021-11-25 07:49 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/auth_page_blue_background.xml
> +    <solid android:color="#004481" />
color ებში გაიტანე

2021-11-25 07:49 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/splash_back_ground.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
ესეც

2021-11-25 07:49 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/circular_button.xml
> +    <solid android:color="#4CABCE"/>
ესეც

2021-11-25 08:03 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/circular_button.xml
> +    <solid android:color="#4CABCE"/>
აუ არადა დავუარე და გამომრჩენია <3 :დ

2021-11-25 08:35 UTC, giorgiqemoklidze approved these changes

2021-11-25 09:00 UTC, AnaRusadze requested changes

2021-11-25 09:00 UTC, AnaRusadze commented on app/src/main/res/layout/splash_fragment.xml
> +        android:id="@+id/imageView"
imageView imageView2? გადაარქვი

2021-11-26 10:40 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/auth_page_blue_background.xml
> +    <solid android:color="#004481" />
done

2021-11-26 10:40 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/circular_button.xml
> +    <solid android:color="#4CABCE"/>
done

2021-11-26 10:40 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/login_fragment.xml
> +                android:textColor="#004481"
done

2021-11-26 10:41 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/splash_fragment.xml
> +        android:id="@+id/imageView"
done

2021-11-26 10:42 UTC, AleksandreGalogreBaramidze commented
@giorgiqemoklidze ჩამიმერჯე

2021-11-26 10:47 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-26 12:38 UTC, AnaRusadze approved these changes

2021-11-26 12:38 UTC, merged